discourse/DiscoTOC

common/header.html
This PR adds support for non-Latin characters, which were previously stripped out by RegEx. This means that DiscoTOC now supports all languages.
The PR also includes a fix for snail-like scrolling that occurs on first view, where the TOC doesn't navigate to the correct header. This resolves itself on secondary views, but this PR eliminates the need for that.
=> FEATURE: support non-Latin characters

common/common.scss, javascripts/discourse/connectors/after-topic-progress/d-toc-mini.hbs
- ensure element height fits in short viewports
- use `d-button` element
=> UX: A couple of small fixes

common/common.scss, javascripts/discourse/connectors/below-docs-topic/d-toc-wrapper.hbs, javascripts/discourse/initializers/disco-toc-main.js
The refactor in https://github.com/discourse/DiscoTOC/commit/20366c671dc951c2cbca86b119b2008e1e9831d3 inadvertently removed support in Docs (because Docs uses a special template for the topic that doesn't use core's post stream events.) 
Accompanies https://github.com/discourse/discourse-docs/pull/75.
=> FIX: Restore support for docs plugin

common/common.scss, javascripts/discourse/initializers/disco-toc-main.js
- fix `Ctrl` + clicking on other links in a page with DiscoTOC
- visually show third level in TOC
- fix overlapping levels for long TOCs
- remove support for h6 headings
=> DEV: A few more fixes

common/common.scss
The 225px width was causing some layout issues with the OP's avatar.
=> UX: Fix bug with desktop widths < 1045px

common/common.scss
Should fix most issues. 
Note that this commit might be temporary, @CvX has a PR in core to remove `float:left` for this element in core: https://github.com/discourse/discourse/pull/15693.
=> UX: Fix layout issues in < 1035px wide windows (take 2)

common/common.scss
We previously added a reset to the topic body layout of the first post to fix some wrapping issues, but looks like a) the reset is no longer necessary and b) it causes jumping on scroll. So let's remove it.
=> FIX: Stop jumping on scroll

javascripts/discourse/initializers/disco-toc-main.js
When the loading slider component is active, the TOC was incorrectly being shown when navigating within the app. For example, when clicking a link to a topic's nth post, its TOC aws being displayed (when it should have only displayed if navigating to the OP).
Note the `d-toc-timeline-visible` class is still used, it is just toggled on/off via the `topic:current-post-changed` event only.
=> FIX: Compatibility with loading slider

javascripts/discourse/initializers/disco-toc-main.js, locales/en.yml, locales/zh_CN.yml, settings.yml, test/acceptance/toc-test.js
This PR adds two settings. 
One allows admins to select a list of categories that will automatically enable the TOC if the topic category matches.
The other does the same but with tags. 
Note that the topic still needs to have the other requirements for TOC, such as having headings. Also, this will still only apply to the first post.
This PR also moves some setting descriptions to the appropriate place. 
It also uses `pretender` for the tests instead of generating the fixture manually.
=> FEATURE: Automatically add TOC based on topic category / tags

javascripts/discourse/initializers/disco-toc-main.js
Adding `#` to empty link `href`. This should fix a hard to reproduce issue where on click of link, page reloads.
=> FIX: Add # to empty hrefs

javascripts/discourse/initializers/disco-toc-main.js, settings.yml, test/acceptance/toc-test.js
The theme setting `TOC_min_heading` will decide whether the TOC should display or not based on the number of heading available in the post.
=> FEATURE: new theme setting to disable TOC in posts with less headings.

test/acceptance/toc-composer-test.js
Core now needs tests to set a default composer category.
=> DEV: Fix tests

common/common.scss
The TOC header in the composer preview went behind images when scrolling and had a useless transparent (same color as the background) 2px top border that didn't align properly with the rest of the layout.
Before:
After:
=> UX: fix TOC header in composer preview when creating a topic

javascripts/discourse/connectors/after-topic-progress/d-toc-mini.hbs, javascripts/discourse/connectors/after-topic-progress/d-toc-mini.js
Why this change?
We've established internally that this is the better way to do things
=> DEV: Convert connector file to use glimmer component

javascripts/discourse/connectors/after-topic-progress/d-toc-mini.hbs
This was inadvertently removed in 4ae24c6edc9b5c3633a5c3f97f566c9f10abdddc, and led to the UI appearing on all topics
=> FIX: Restore wrapper element for d-toc-mini

common/common.scss, javascripts/discourse/initializers/disco-toc-main.js
This adjusts some specificity for mobile to fix a couple follow-up issues to https://github.com/discourse/DiscoTOC/commit/a089aa0289968a08084bb5cf408cd9dd2414af68
1. The timeline button was appearing in some mobile cases where it shouldn't 
2. The mobile timeline links weren't always working because they were getting caught by 
```js
if (
!classNames.some((className) =>
document.body.classList.contains(className)
)
) {
return;
}
```
=> FIX: adjust mobile specificity 

spec/system/discotoc_progress_user_spec.rb
The CSS uses
`.timeline-fullscreen .timeline-toggle { display: none; }`
so in theory it shouldn't be possible for the page to have this element visible! perhaps `.timeline-toggle` wasn't specific enough so let's try to be 1:1 with `.timeline-fullscreen .timeline-toggle`
=> DEV: use more specific selector to avoid flaky test

javascripts/discourse/initializers/disco-toc-composer.js
At the moment, staff is also limited by their trust level, which is contrary to how we usually handle trust levels.
=> UX: ignore trust level setting for staff accounts

javascripts/discourse/components/toc-timeline.gjs
Add class to body when d-toc is installed, even when it isnt rendered.
=> DEV: Update toc-timeline.gjs

common/common.scss, javascripts/discourse/components/toc-contents.gjs, javascripts/discourse/components/toc-heading.gjs, javascripts/discourse/components/toc-mini.gjs, javascripts/discourse/initializers/disco-toc-composer.js, javascripts/discourse/services/toc-processor.js, locales/en.yml, settings.yml, spec/system/discotoc_author_spec.rb, spec/system/discotoc_progress_user_spec.rb, spec/system/discotoc_timeline_user_spec.rb
This commit adds an optional (defaultly disabled) setting that allows enabling a TOC for replies. TOCs for replies are not affected by autoTOC settings like `auto_TOC_tags` and must be inserted manually.
https://github.com/user-attachments/assets/6a66694c-e9f7-4d8c-ba99-99a7a8633548
=> FEATURE: Allow TOC for replies

spec/system/discotoc_timeline_user_spec.rb
This is working with selenium, but this won't be working with playwright which is less permissive on selectors.
=> DEV: uses correct selector
